[font]
size = 8

[font.normal]
family = "Blex Mono Nerd Font"

[window]
opacity = 0.85

[general]
import = ["/home/tristan/.config/alacritty/fluoromachine.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1.4"
